# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: publish

on:
  workflow_dispatch:
  #release:
  #  types: [created]

jobs:
  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.5.0
      - run: yarn
      - run: yarn build
      - run: XUI_VERSION=$(npm version patch) >> $GITHUB_ENV
        working-directory: packages/core
      - run: npm publish
        working-directory: packages/core
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: viewdo/x-ui-docs
          tag_with_ref: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.XUI_VERSION }}
          release_name: Release ${{ env.XUI_VERSION }}
          body: |
            Auto release  ${{ env.XUI_VERSION }}
          draft: true
          prerelease: true
