# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [created]

jobs:
  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
      - run: yarn version patch
        working-directory: packages/core
      - run: npm publish
        working-directory: packages/core
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}
  docker:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: viewdo/x-ui-docs
          tag_with_ref: true
